# Generated by Django 2.2.2 on 2019-06-28 09:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=600)),
                ('created', models.DateTimeField(verbose_name='date/time created')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=600)),
                ('start', models.DateTimeField(verbose_name='date/time created')),
                ('end', models.DateTimeField(default=datetime.datetime.now, verbose_name='date/time created')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Issue')),
            ],
        ),
    ]
